name: mbti
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rflutter_alert: ^2.0.4
  vertical_tabs: ^0.2.0
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - infoText/
    - Descriptions/INTJ/
    - Descriptions/ISTJ/
    - Descriptions/ENTJ/
    - Descriptions/ESTJ/
    - Descriptions/INFJ/
    - Descriptions/ENFJ/
    - Descriptions/INFP/
    - Descriptions/ENFP/
    - Descriptions/ISTP/
    - Descriptions/ISFP/
    - Descriptions/ESFP/
    - Descriptions/ESTP/
    - Descriptions/ISFJ/
    - Descriptions/ESFJ/
    - Descriptions/ENTP/
    - Descriptions/INTP/

  fonts:
    - family: MyFont
      fonts:
        - asset: fonts/Cardinal-Valentino.ttf

    - family: MyFont2
      fonts:
        - asset: fonts/Le-chant-des-Albatros.ttf

    - family: MyFont3
      fonts:
        - asset: fonts/bBiketoWork.ttf

flutter icons:
  image_path: "icons/11.jpg"
  android: true
  ios: true
  flutter_lints: ^1.0.0